### ISSUE TITLE
Cannot insert timesheets

### ISSUE THREAD

**Issue by dinindu-fernando** [MYOB-Technology/AccountRight_Live_API_.Net_SDK#37]
Hi Guys,
I have integrated MYOB AccountRight with our application and currently in the process of integrating Timesheets. 

I found that the MYOB.AccountRight.SDK.Services.Payroll.TimesheetService doesn't have an option to insert new timesheets like in other Services. However, it has a method to Update an existing timesheet.

Can somebody please give me an example to create a timesheet with .Net SDK.

Appreciate any help on this regard.

Thanks,
Dinindu

**Comment by devjack** [comment]
Hi @dinindu-fernando,

The timesheet/payroll endpoint uses PUT and the JSON payload to 'update' an empty timesheet rather than create a new one.  The full endpoint docs are here: http://developers.myob.com/api/accountright/v2/payroll/timesheet/ (note it also only contains an update or PUT).

Note that internally within the Timesheet service we have helper functions that convert the datetime params for the query string [TimesheetService.cs:396](https://github.com/MYOB-Technology/AccountRight_Live_API_.Net_SDK/blob/master/MYOB.API.SDK/SDK/Services/Version2/Payroll/TimesheetService.cs#L396)

If you drop us an email at developers [at] myob [dot] com we'll see if we can help you out for your specific case.

Cheers!

**Comment by dinindu-fernando** [comment]
Hi @devjack,
Thanks for your prompt response. I will look into this and let you know if I hit a road block :)

Cheers,
Dinindu

**Comment by dipansaha** [comment]
Hi Dinindu,
Did you able to figure it out? Can you create new timesheet uding timesheetservice update method? 

@devjack:
You have said update / put can update existing empty timesheet. Is that mean we can have new timesheet object and calling update will create new timesheet? Or do we have to create timesheet manually in accountright and then onlycan update through sdk?

Thanks
Dipan

**Comment by devjack** [comment]
In this particular case it might be worth thinking of timesheets as an excel spreadsheet.  Only that you 'update' cells rather than create them.  Similarly the timesheet endpoint only lets you update a timesheet (which will both create or update/overwrite entries where appropriate).

**Comment by dipansaha** [comment]
It makes sense now. Thanks for your reply @devjack

**Comment by chanrahman** [comment]
Can you help me, when i try to timsheetService.GetRange with query top=1000, i get this error

`   at MYOB.AccountRight.SDK.Communication.WebRequestFactory.Create(Uri requestUri, String acceptEncoding) in c:\projects\accountright-live-api-net-sdk\MYOB.API.SDK\SDK\Communication\WebRequestFactory.cs:line 48
   at MYOB.AccountRight.SDK.Services.ServiceBase.<>c__DisplayClass10`1.<MakeApiGetRequestDelegate>b__f(OAuthTokens response) in c:\projects\accountright-live-api-net-sdk\MYOB.API.SDK\SDK\Services\ServiceBase.cs:line 78
   at MYOB.AccountRight.SDK.Services.ServiceBase.WrapApiRequestWithOAuthRenew(Action`1 apiRequest, Action`2 onError) in c:\projects\accountright-live-api-net-sdk\MYOB.API.SDK\SDK\Services\ServiceBase.cs:line 56
   at MYOB.AccountRight.SDK.Services.ServiceBase.MakeApiGetRequestDelegate[T](Uri uri, ICompanyFileCredentials credentials, Action`2 onComplete, Action`2 onError, String eTag) in c:\projects\accountright-live-api-net-sdk\MYOB.API.SDK\SDK\Services\ServiceBase.cs:line 75
   at MYOB.AccountRight.SDK.Services.ServiceBase.MakeApiGetRequestSync[T](Uri uri, ICompanyFileCredentials credentials, String eTag) in c:\projects\accountright-live-api-net-sdk\MYOB.API.SDK\SDK\Services\ServiceBase.cs:line 133
   at MYOB.AccountRight.SDK.Services.Payroll.TimesheetService.GetRange(CompanyFile cf, String queryString, ICompanyFileCredentials credentials) in c:\projects\accountright-live-api-net-sdk\MYOB.API.SDK\SDK\Services\Version2\Payroll\TimesheetService.cs:line 305`
